import type { Profile, Inquiry, User, JournalEntry, SuccessStory, Testimonial } from './types';

// Unsplash photo IDs for elegant portrait placeholders (no API key needed)
const portrait = (seed: string) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=900&q=80`;

const PHOTOS = {
  // Brides
  aanya: [portrait('photo-1494790108377-be9c29b29330'), portrait('photo-1517841905240-472988babdf9')],
  priya: [portrait('photo-1438761681033-6461ffad8d80'), portrait('photo-1534528741775-53994a69daeb')],
  kavya: [portrait('photo-1531746020798-e6953c6e8e04'), portrait('photo-1573496359142-b8d87734a5a2')],
  ishita: [portrait('photo-1517365830460-955ce3ccd263'), portrait('photo-1502823403499-6ccfcf4fb453')],
  ananya: [portrait('photo-1488426862026-3ee34a7d66df'), portrait('photo-1503467913725-7fa8a0b07475')],
  diya: [portrait('photo-1542596594-649edbc13630'), portrait('photo-1521252659862-eec69941b071')],
  saanvi: [portrait('photo-1469334031218-e382a71b716b'), portrait('photo-1485518882345-15568b007407')],
  myra: [portrait('photo-1521146764736-56c929d59c83'), portrait('photo-1509967419530-da38b4704bc6')],
  anika: [portrait('photo-1554151228-14d9def656e4'), portrait('photo-1487412720507-e7ab37603c6f')],
  riya: [portrait('photo-1502823403499-6ccfcf4fb453'), portrait('photo-1496440737103-cd596325d314')],
  tara: [portrait('photo-1496440737103-cd596325d314'), portrait('photo-1496359070269-43ec3a4b4243')],
  nitya: [portrait('photo-1503467913725-7fa8a0b07475'), portrait('photo-1531123897727-8f129e1688ce')],
  zoya: [portrait('photo-1488426862026-3ee34a7d66df'), portrait('photo-1502823403499-6ccfcf4fb453')],
  kiara: [portrait('photo-1502323777036-f29e3972d82f'), portrait('photo-1525134479668-1bee5c7c6845')],
  mira: [portrait('photo-1496440737103-cd596325d314'), portrait('photo-1488426862026-3ee34a7d66df')],
  // Grooms
  arjun: [portrait('photo-1507003211169-0a1dd7228f2d'), portrait('photo-1500648767791-00dcc994a43e')],
  rohan: [portrait('photo-1506794778202-cad84cf45f1d'), portrait('photo-1492562080023-ab3db95bfbce')],
  aditya: [portrait('photo-1463453091185-61582044d556'), portrait('photo-1507081323647-4d250478b919')],
  vivaan: [portrait('photo-1519085360753-af0119f7cbe7'), portrait('photo-1492562080023-ab3db95bfbce')],
  reyansh: [portrait('photo-1488161628813-04466f872be2'), portrait('photo-1500648767791-00dcc994a43e')],
  aarav: [portrait('photo-1463453091185-61582044d556'), portrait('photo-1492562080023-ab3db95bfbce')],
  vihaan: [portrait('photo-1481824429379-07aa5e5b0739'), portrait('photo-1507003211169-0a1dd7228f2d')],
  muhammad: [portrait('photo-1500648767791-00dcc994a43e'), portrait('photo-1506794778202-cad84cf45f1d')],
  arnav: [portrait('photo-1500048993953-d23a436266cf'), portrait('photo-1463453091185-61582044d556')],
  ishaan: [portrait('photo-1488161628813-04466f872be2'), portrait('photo-1519085360753-af0119f7cbe7')],
  dhruv: [portrait('photo-1507081323647-4d250478b919'), portrait('photo-1500648767791-00dcc994a43e')],
  krishna: [portrait('photo-1492562080023-ab3db95bfbce'), portrait('photo-1481824429379-07aa5e5b0739')],
  ayaan: [portrait('photo-1500048993953-d23a436266cf'), portrait('photo-1488161628813-04466f872be2')],
  atharv: [portrait('photo-1506794778202-cad84cf45f1d'), portrait('photo-1500648767791-00dcc994a43e')],
  kabir: [portrait('photo-1519085360753-af0119f7cbe7'), portrait('photo-1463453091185-61582044d556')],
};

export const seedProfiles: Profile[] = [
  // ───── BRIDES ─────
  {
    id: 'p-bride-aanya', slug: 'aanya-sharma', type: 'bride',
    name: 'Aanya Sharma', age: 26, height: '5\'5"', maritalStatus: 'Never Married',
    photos: PHOTOS.aanya,
    headline: 'A designer who finds poetry in everyday objects',
    about: 'I am a textile designer who believes beauty lies in the smallest details — a hand-stitched hem, the grain of natural linen, the curve of a tea cup at sunrise. I split my week between my studio in Bandra and the reading room at the Asiatic Society. Looking for a partner who appreciates slow mornings and slow conversations.',
    education: { degree: 'B.Des Textile Design', institution: 'NIFT Mumbai', field: 'Design' },
    profession: { title: 'Senior Textile Designer', company: 'Atelier Vriksh', income: '₹18 LPA' },
    location: { city: 'Mumbai', state: 'Maharashtra', country: 'India', nativePlace: 'Jaipur' },
    family: { father: 'Mr. Vikram Sharma (Architect)', mother: 'Mrs. Meera Sharma (Classical Vocalist)', siblings: 'One younger brother (Engineer, NIT Trichy)', familyType: 'Nuclear, Upper-middle class', values: 'Progressive, rooted in Hindu-Jain traditions, vegetarian' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Block printing', 'Classical music', 'Long walks', 'Cooking'], languages: ['Hindi', 'English', 'Marwari', 'French (basic)'] },
    religion: { religion: 'Hindu', community: 'Jain-Agrawal heritage', subCommunity: 'Vaishya' },
    partnerExpectations: 'A well-educated, emotionally mature partner who values art, family, and shared silence. Preferably a professional in design, medicine, law, or finance. Should respect cultural traditions while embracing modern values. Age 28-34.',
    createdAt: '2025-08-12T10:00:00Z', featured: true,
  },
  {
    id: 'p-bride-priya', slug: 'priya-iyer', type: 'bride',
    name: 'Dr. Priya Iyer', age: 27, height: '5\'4"', maritalStatus: 'Never Married',
    photos: PHOTOS.priya,
    headline: 'Pediatrician by profession, aspiring novelist by night',
    about: 'Healing children is my day job; my nights belong to unfinished short stories and cups of filter coffee. I run free health camps in Bangalore slums every Sunday with two friends from med school. Family, kindness, and intellectual honesty are non-negotiable for me.',
    education: { degree: 'MBBS, MD Pediatrics', institution: 'St. John\'s Medical College, Bangalore', field: 'Medicine' },
    profession: { title: 'Pediatrician', company: 'Cloudnine Hospital', income: '₹22 LPA' },
    location: { city: 'Bangalore', state: 'Karnataka', country: 'India', nativePlace: 'Chennai' },
    family: { father: 'Late Prof. R. Iyer (Mathematician)', mother: 'Mrs. Lakshmi Iyer (Retired Sanskrit teacher)', siblings: 'One elder sister (Software engineer, Seattle)', familyType: 'Joint, well-knit', values: 'Tamil Brahmin, Iyer, traditional with progressive outlook' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Writing', 'Bharatanatyam', 'Reading fiction', 'Trekking'], languages: ['Tamil', 'English', 'Hindi', 'Sanskrit'] },
    religion: { religion: 'Hindu', community: 'Tamil Brahmin', subCommunity: 'Iyer' },
    partnerExpectations: 'A doctor, engineer, or researcher who is grounded, family-oriented, and shares a love for books or the outdoors. Age 29-34. Caste no bar for the right person.',
    createdAt: '2025-08-20T10:00:00Z', featured: true,
  },
  {
    id: 'p-bride-kavya', slug: 'kavya-reddy', type: 'bride',
    name: 'Kavya Reddy', age: 25, height: '5\'6"', maritalStatus: 'Never Married',
    photos: PHOTOS.kavya,
    headline: 'Architect restoring heritage homes in Hyderabad',
    about: 'I spend my days studying old Nizami mansions and bringing them back to life. I love nothing more than a long road trip with good music and a thermos of chai. Hoping to meet someone who treats curiosity as a lifestyle, not a phase.',
    education: { degree: 'M.Arch (Conservation)', institution: 'CEPT University, Ahmedabad', field: 'Architecture' },
    profession: { title: 'Associate Architect', company: 'Studio Mohalla', income: '₹16 LPA' },
    location: { city: 'Hyderabad', state: 'Telangana', country: 'India', nativePlace: 'Hyderabad' },
    family: { father: 'Mr. K. R. Reddy (Businessman)', mother: 'Mrs. Sunitha Reddy (Homemaker)', siblings: 'Two brothers — one CA, one studying medicine', familyType: 'Nuclear', values: 'Telugu Reddy, traditional vegetarian, liberal values' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Heritage walks', 'Photography', 'Sketching', 'Carnatic music'], languages: ['Telugu', 'English', 'Hindi', 'Urdu (basic)'] },
    religion: { religion: 'Hindu', community: 'Telugu', subCommunity: 'Reddy' },
    partnerExpectations: 'An empathetic, well-traveled professional who values culture and conversation. Age 27-32. Open to inter-caste.',
    createdAt: '2025-09-01T10:00:00Z',
  },
  {
    id: 'p-bride-ishita', slug: 'ishita-patel', type: 'bride',
    name: 'CA Ishita Patel', age: 26, height: '5\'3"', maritalStatus: 'Never Married',
    photos: PHOTOS.ishita,
    headline: 'Numbers by day, mandala art by evening',
    about: 'I clear audits for a mid-size firm and unwind by drawing intricate mandalas that I sell at small art markets on weekends. Family means everything to me, but so does financial independence — and I want a partner who understands both.',
    education: { degree: 'Chartered Accountant, B.Com Hons', institution: 'HL College of Commerce, Ahmedabad', field: 'Finance' },
    profession: { title: 'Audit Manager', company: 'Deloitte', income: '₹19 LPA' },
    location: { city: 'Ahmedabad', state: 'Gujarat', country: 'India', nativePlace: 'Surat' },
    family: { father: 'Mr. Hitesh Patel (Diamond merchant)', mother: 'Mrs. Nisha Patel (School principal)', siblings: 'Younger brother (BBA, joining family business)', familyType: 'Joint, traditional Gujarati', values: 'Patel, Jain-adjacent, vegetarian, teetotaler' },
    lifestyle: { diet: 'Vegetarian (Jain)', hobbies: ['Mandala art', 'Garba', 'Cooking Gujarati food', 'Travel'], languages: ['Gujarati', 'Hindi', 'English'] },
    religion: { religion: 'Hindu', community: 'Gujarati', subCommunity: 'Patel' },
    partnerExpectations: 'A Chartered Accountant, MBA, or business owner from a respectable Gujarati family. Age 28-33. Should value family, hard work, and tradition.',
    createdAt: '2025-09-05T10:00:00Z', featured: true,
  },
  {
    id: 'p-bride-ananya', slug: 'ananya-kapoor', type: 'bride',
    name: 'Ananya Kapoor', age: 28, height: '5\'7"', maritalStatus: 'Never Married',
    photos: PHOTOS.ananya,
    headline: 'Marketing director with a passion for vintage cinema',
    about: 'I head brand for a D2C wellness startup, run half marathons when I can, and I have an embarrassingly large collection of black-and-white Bollywood posters. I am looking for someone who makes me laugh and who would never miss a Mehfil night.',
    education: { degree: 'MBA (Marketing), B.A. English Lit', institution: 'IIM Lucknow / Lady Shri Ram', field: 'Business' },
    profession: { title: 'Marketing Director', company: 'Plix (Wellness)', income: '₹42 LPA' },
    location: { city: 'Delhi', state: 'Delhi', country: 'India', nativePlace: 'Delhi' },
    family: { father: 'Justice (Retd.) S. K. Kapoor', mother: 'Mrs. Renu Kapoor (Painter)', siblings: 'One elder brother (Investment banker, London)', familyType: 'Nuclear', values: 'Punjabi Khatri, progressive, cultural, non-vegetarian at home' },
    lifestyle: { diet: 'Non-vegetarian', hobbies: ['Running', 'Vintage Bollywood', 'Wine tasting', 'Yoga'], languages: ['Hindi', 'English', 'Punjabi'] },
    religion: { religion: 'Hindu', community: 'Punjabi', subCommunity: 'Khatri' },
    partnerExpectations: 'An MBA, lawyer, or entrepreneur from a cosmopolitan background. Age 30-36. Should be well-read, kind, and confident.',
    createdAt: '2025-09-08T10:00:00Z',
  },
  {
    id: 'p-bride-diya', slug: 'diya-mehta', type: 'bride',
    name: 'Diya Mehta', age: 25, height: '5\'5"', maritalStatus: 'Never Married',
    photos: PHOTOS.diya,
    headline: 'Software engineer building sustainable tech',
    about: 'I write code at a climate-tech startup by day, and I run a small pottery studio from my garage on weekends. Looking for a partner who is curious about everything and kind without trying.',
    education: { degree: 'B.Tech Computer Science', institution: 'IIT Bombay', field: 'Engineering' },
    profession: { title: 'Senior Software Engineer', company: 'GreenTensor AI', income: '₹32 LPA' },
    location: { city: 'Pune', state: 'Maharashtra', country: 'India', nativePlace: 'Pune' },
    family: { father: 'Mr. Sanjay Mehta (CA)', mother: 'Mrs. Anjali Mehta (Doctor)', siblings: 'One younger sister (Architect, studying in Italy)', familyType: 'Nuclear', values: 'Gujarati, vegetarian-friendly home, modern' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Pottery', 'Cycling', 'Coding side projects', 'Reading'], languages: ['English', 'Hindi', 'Gujarati', 'Marathi'] },
    religion: { religion: 'Hindu', community: 'Gujarati', subCommunity: 'Lohana' },
    partnerExpectations: 'A tech professional or entrepreneur who values sustainability and creativity. Age 27-32. Caste no bar.',
    createdAt: '2025-09-10T10:00:00Z',
  },
  {
    id: 'p-bride-saanvi', slug: 'saanvi-joshi', type: 'bride',
    name: 'Saanvi Joshi', age: 27, height: '5\'4"', maritalStatus: 'Never Married',
    photos: PHOTOS.saanvi,
    headline: 'Investigative journalist covering rural India',
    about: 'I have filed stories from a flood in Assam and a panchayat in Rajasthan. When I am home, I cook elaborate Rajasthani thalis and read Hindi poetry. Looking for someone whose ambition is matched by their empathy.',
    education: { degree: 'Masters in Journalism', institution: 'ACJ, Chennai', field: 'Media' },
    profession: { title: 'Senior Correspondent', company: 'The Caravan', income: '₹14 LPA' },
    location: { city: 'Jaipur', state: 'Rajasthan', country: 'India', nativePlace: 'Jodhpur' },
    family: { father: 'Mr. Pradeep Joshi (School principal)', mother: 'Mrs. Kavita Joshi (Government officer)', siblings: 'One elder brother (IAS officer)', familyType: 'Nuclear', values: 'Brahmin, Joshi, traditional vegetarian' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Reading Hindi literature', 'Travel', 'Cooking', 'Bharatnatyam'], languages: ['Hindi', 'English', 'Marwari', 'Sanskrit'] },
    religion: { religion: 'Hindu', community: 'Rajasthani', subCommunity: 'Brahmin (Joshi)' },
    partnerExpectations: 'An educated, socially conscious partner from a cultured family. Age 29-33. Should be respectful and supportive of an independent woman.',
    createdAt: '2025-09-12T10:00:00Z', featured: true,
  },
  {
    id: 'p-bride-myra', slug: 'myra-khan', type: 'bride',
    name: 'Myra Khan', age: 26, height: '5\'6"', maritalStatus: 'Never Married',
    photos: PHOTOS.myra,
    headline: 'Lawyer specializing in human rights',
    about: 'I work with a small NGO on education rights for marginalized children in Uttar Pradesh. I love Awadhi food, ghazals, and the architecture of Lucknow\'s old city. Looking for an equal — someone who stands for something.',
    education: { degree: 'BA LLB Hons', institution: 'NALSAR, Hyderabad', field: 'Law' },
    profession: { title: 'Associate Lawyer', company: 'Citizens for Justice', income: '₹13 LPA' },
    location: { city: 'Lucknow', state: 'Uttar Pradesh', country: 'India', nativePlace: 'Lucknow' },
    family: { father: 'Mr. Javed Khan (Civil engineer)', mother: 'Mrs. Farhat Khan (College professor)', siblings: 'Two younger brothers — one doctor, one studying engineering', familyType: 'Nuclear', values: 'Muslim, Sunni, educated and liberal family' },
    lifestyle: { diet: 'Non-vegetarian (halal)', hobbies: ['Reading Urdu poetry', 'Heritage walks', 'Cooking', 'Henna art'], languages: ['Urdu', 'Hindi', 'English', 'Arabic (basic)'] },
    religion: { religion: 'Muslim', community: 'Sunni', subCommunity: 'Syed' },
    partnerExpectations: 'A professional from a progressive Muslim family. Age 28-33. Should value education, family, and social impact.',
    createdAt: '2025-09-14T10:00:00Z',
  },
  {
    id: 'p-bride-anika', slug: 'anika-singh', type: 'bride',
    name: 'Dr. Anika Singh', age: 28, height: '5\'5"', maritalStatus: 'Never Married',
    photos: PHOTOS.anika,
    headline: 'Physics professor with a love for mountains',
    about: 'I teach quantum mechanics at Punjab Engineering College and spend my summers in the Himalayas. I am looking for a partner who loves learning as much as I do.',
    education: { degree: 'PhD Physics', institution: 'IISc Bangalore', field: 'Academia' },
    profession: { title: 'Assistant Professor', company: 'PEC Chandigarh', income: '₹15 LPA' },
    location: { city: 'Chandigarh', state: 'Punjab', country: 'India', nativePlace: 'Amritsar' },
    family: { father: 'Brig. (Retd.) J. S. Singh', mother: 'Mrs. Harpreet Singh (Homemaker)', siblings: 'One elder brother (Army officer)', familyType: 'Military, nuclear', values: 'Sikh Punjabi, modern, vegetarian' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Trekking', 'Reading physics & fiction', 'Yoga', 'Cooking'], languages: ['Punjabi', 'Hindi', 'English'] },
    religion: { religion: 'Sikh', community: 'Punjabi', subCommunity: 'Jat' },
    partnerExpectations: 'An academic, engineer, or scientist who is curious, kind, and loves the outdoors. Age 30-34.',
    createdAt: '2025-09-15T10:00:00Z',
  },
  {
    id: 'p-bride-riya', slug: 'riya-bose', type: 'bride',
    name: 'Riya Bose', age: 26, height: '5\'4"', maritalStatus: 'Never Married',
    photos: PHOTOS.riya,
    headline: 'Visual artist and gallery curator',
    about: 'My studio is in a converted warehouse in Salt Lake. I work mostly with watercolors and reclaimed textiles, and I curate a small exhibition space for emerging Bengali artists. Looking for someone who finds beauty in imperfection.',
    education: { degree: 'BFA Painting, MA Art History', institution: 'Kala Bhavana, Santiniketan / JNU', field: 'Arts' },
    profession: { title: 'Artist & Independent Curator', company: 'Self-employed', income: '₹9 LPA' },
    location: { city: 'Kolkata', state: 'West Bengal', country: 'India', nativePlace: 'Kolkata' },
    family: { father: 'Mr. Subroto Bose (Retired banker)', mother: 'Mrs. Indrani Bose (English professor)', siblings: 'One younger sister (Dancer)', familyType: 'Nuclear, intellectual', values: 'Bengali Brahmin, liberal, non-vegetarian-friendly, fish at home' },
    lifestyle: { diet: 'Pescatarian', hobbies: ['Painting', 'Reading', 'Visiting art fairs', 'Cinema'], languages: ['Bengali', 'English', 'Hindi'] },
    religion: { religion: 'Hindu', community: 'Bengali', subCommunity: 'Brahmin' },
    partnerExpectations: 'An artist, writer, or academic with depth and kindness. Age 28-33. Should appreciate art and conversation.',
    createdAt: '2025-09-17T10:00:00Z',
  },
  {
    id: 'p-bride-tara', slug: 'tara-malhotra', type: 'bride',
    name: 'Tara Malhotra', age: 27, height: '5\'6"', maritalStatus: 'Never Married',
    photos: PHOTOS.tara,
    headline: 'Founder of a craft chocolate brand',
    about: 'I left consulting to start a bean-to-bar chocolate company in Goa. I travel to Kerala every quarter to source cacao from tribal farmers. I need a partner who is entrepreneurial and doesn\'t mind a chaotic kitchen.',
    education: { degree: 'MBA, B.Com', institution: 'ISB Hyderabad / SRCC', field: 'Business' },
    profession: { title: 'Founder & CEO', company: 'Terra Cocoa Co.', income: '₹28 LPA (variable)' },
    location: { city: 'Mumbai', state: 'Maharashtra', country: 'India', nativePlace: 'Delhi' },
    family: { father: 'Mr. Rajiv Malhotra (Industrialist)', mother: 'Mrs. Nandini Malhotra (Interior designer)', siblings: 'Two brothers — one fintech, one chef', familyType: 'Joint, business', values: 'Punjabi Hindu, progressive, foodie family' },
    lifestyle: { diet: 'Non-vegetarian', hobbies: ['Cooking', 'Sailing', 'Sourcing cacao', 'Yoga'], languages: ['Hindi', 'English', 'Punjabi', 'French'] },
    religion: { religion: 'Hindu', community: 'Punjabi', subCommunity: 'Khatri' },
    partnerExpectations: 'An entrepreneur, consultant, or chef. Age 29-34. Should be supportive of my travel and food passions.',
    createdAt: '2025-09-18T10:00:00Z', featured: true,
  },
  {
    id: 'p-bride-nitya', slug: 'nitya-pillai', type: 'bride',
    name: 'Nitya Pillai', age: 25, height: '5\'5"', maritalStatus: 'Never Married',
    photos: PHOTOS.nitya,
    headline: 'Classical dancer and choreographer',
    about: 'I trained under Guru Leela Samson for 18 years and now perform Mohiniyattam internationally. I run a small dance school in Mylapore for underprivileged children. Looking for a partner who appreciates art but also has their own dreams.',
    education: { degree: 'BA Dance, MA Performing Arts', institution: 'Kalakshetra, Chennai', field: 'Arts' },
    profession: { title: 'Dancer & Choreographer', company: 'Independent / Visiting faculty', income: '₹10 LPA' },
    location: { city: 'Chennai', state: 'Tamil Nadu', country: 'India', nativePlace: 'Thiruvananthapuram' },
    family: { father: 'Mr. Gopalan Pillai (Retired banker)', mother: 'Mrs. Sumitha Pillai (Music teacher)', siblings: 'One younger brother (Software engineer)', familyType: 'Nuclear, traditional', values: 'Nair, Kerala Hindu, vegetarian, temple-going' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Dance', 'Carnatic music', 'Reading', 'Cooking'], languages: ['Malayalam', 'Tamil', 'English', 'Hindi'] },
    religion: { religion: 'Hindu', community: 'Kerala', subCommunity: 'Nair' },
    partnerExpectations: 'An engineer, doctor, or artist who values tradition, arts, and family. Age 27-32.',
    createdAt: '2025-09-19T10:00:00Z',
  },
  {
    id: 'p-bride-zoya', slug: 'zoya-ahmed', type: 'bride',
    name: 'Zoya Ahmed', age: 28, height: '5\'5"', maritalStatus: 'Never Married',
    photos: PHOTOS.zoya,
    headline: 'Investment banker with a love for calligraphy',
    about: 'I work in the M&A team at a top bank, but my weekends belong to Arabic calligraphy classes and poetry readings at Bangalore Literature Festival. Looking for a partner who is intellectually curious and emotionally steady.',
    education: { degree: 'MBA Finance, BBA', institution: 'IIM Ahmedabad / St. Xavier\'s Mumbai', field: 'Finance' },
    profession: { title: 'Vice President', company: 'JP Morgan', income: '₹58 LPA' },
    location: { city: 'Bangalore', state: 'Karnataka', country: 'India', nativePlace: 'Mumbai' },
    family: { father: 'Mr. Asif Ahmed (Chartered accountant)', mother: 'Mrs. Shaheen Ahmed (Homemaker)', siblings: 'Two siblings — elder sister is a doctor, younger brother is in CA', familyType: 'Nuclear', values: 'Muslim Sunni Bohri, educated liberal family' },
    lifestyle: { diet: 'Non-vegetarian (halal)', hobbies: ['Calligraphy', 'Reading', 'Travel', 'Pottery'], languages: ['English', 'Urdu', 'Hindi', 'Arabic (reading)'] },
    religion: { religion: 'Muslim', community: 'Sunni', subCommunity: 'Bohri' },
    partnerExpectations: 'A finance professional, lawyer, or doctor. Age 30-35. From a progressive Muslim family.',
    createdAt: '2025-09-20T10:00:00Z', featured: true,
  },
  {
    id: 'p-bride-kiara', slug: 'kiara-nair', type: 'bride',
    name: 'Dr. Kiara Nair', age: 26, height: '5\'6"', maritalStatus: 'Never Married',
    photos: PHOTOS.kiara,
    headline: 'Clinical psychologist focused on adolescent therapy',
    about: 'I run a private practice in Kochi and consult at a government hospital once a week. My bookshelf is mostly trauma and attachment theory, but my kitchen is Kerala home cooking at its homeliest. Looking for someone who feels like home.',
    education: { degree: 'MPhil Clinical Psychology', institution: 'NIMHANS, Bangalore', field: 'Healthcare' },
    profession: { title: 'Clinical Psychologist', company: 'Private practice', income: '₹14 LPA' },
    location: { city: 'Kochi', state: 'Kerala', country: 'India', nativePlace: 'Kochi' },
    family: { father: 'Mr. K. P. Nair (Judge)', mother: 'Dr. Latha Nair (Gynecologist)', siblings: 'One elder brother (Cardiologist, UK)', familyType: 'Nuclear, professional', values: 'Kerala Nair, traditional values, modern outlook' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Reading', 'Yoga', 'Beach walks', 'Cooking'], languages: ['Malayalam', 'English', 'Hindi', 'Tamil'] },
    religion: { religion: 'Hindu', community: 'Kerala', subCommunity: 'Nair' },
    partnerExpectations: 'A doctor, engineer, or lawyer who is kind, stable, and loves travel. Age 28-32.',
    createdAt: '2025-09-21T10:00:00Z',
  },
  {
    id: 'p-bride-mira', slug: 'mira-verma', type: 'bride',
    name: 'Mira Verma', age: 27, height: '5\'7"', maritalStatus: 'Never Married',
    photos: PHOTOS.mira,
    headline: 'Fashion designer showcasing at India Couture Week',
    about: 'I run a small couture house in Hauz Khas that I started with my grandmother\'s embroidery archive. I split time between Delhi and Jaipur. Looking for someone who appreciates craft, conversation, and quiet Sundays.',
    education: { degree: 'B.Des Fashion', institution: 'NIFT Delhi', field: 'Design' },
    profession: { title: 'Fashion Designer & Founder', company: 'Vermā Atelier', income: '₹24 LPA' },
    location: { city: 'Delhi', state: 'Delhi', country: 'India', nativePlace: 'Lucknow' },
    family: { father: 'Mr. Vivek Verma (Hotelier)', mother: 'Mrs. Rashmi Verma (Textile restorer)', siblings: 'One younger brother (Brand strategist)', familyType: 'Nuclear, art-oriented', values: 'Kayastha, progressive, vegetarian' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Embroidery', 'Antique textiles', 'Theatre', 'Travel'], languages: ['Hindi', 'English', 'Urdu'] },
    religion: { religion: 'Hindu', community: 'UP', subCommunity: 'Kayastha' },
    partnerExpectations: 'A creative professional, business owner, or doctor. Age 29-34. Should value aesthetics and tradition.',
    createdAt: '2025-09-22T10:00:00Z', featured: true,
  },

  // ───── GROOMS ─────
  {
    id: 'p-groom-arjun', slug: 'arjun-sharma', type: 'groom',
    name: 'Arjun Sharma', age: 29, height: '5\'11"', maritalStatus: 'Never Married',
    photos: PHOTOS.arjun,
    headline: 'Investment banker who cooks Sunday brunch',
    about: 'I lead the consumer tech team at a global bank in Mumbai. Outside of work I host elaborate brunches for friends, mentor college students, and run a small podcast on Indian business stories. Looking for an equal partner to share a life and a kitchen.',
    education: { degree: 'MBA Finance', institution: 'IIM Bangalore', field: 'Finance' },
    profession: { title: 'Vice President', company: 'Morgan Stanley', income: '₹62 LPA' },
    location: { city: 'Mumbai', state: 'Maharashtra', country: 'India', nativePlace: 'Delhi' },
    family: { father: 'Mr. Ramesh Sharma (CA)', mother: 'Mrs. Sushma Sharma (Homemaker)', siblings: 'One elder sister (Doctor, US)', familyType: 'Nuclear, well-settled', values: 'Punjabi Hindu, progressive, vegetarian at home' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Cooking', 'Running', 'Podcast', 'Travel'], languages: ['Hindi', 'English', 'Punjabi'] },
    religion: { religion: 'Hindu', community: 'Punjabi', subCommunity: 'Khatri' },
    partnerExpectations: 'An MBA, doctor, or designer from a cosmopolitan family. Age 26-30. Should be independent, kind, and love food.',
    createdAt: '2025-08-15T10:00:00Z', featured: true,
  },
  {
    id: 'p-groom-rohan', slug: 'rohan-iyer', type: 'groom',
    name: 'Rohan Iyer', age: 30, height: '5\'10"', maritalStatus: 'Never Married',
    photos: PHOTOS.rohan,
    headline: 'Software architect building distributed systems',
    about: 'I design infrastructure for fintech at a Bangalore startup. I love Carnatic music, the early morning coffee ritual, and weekends spent tinkering with home automation. Looking for a partner who is intellectually generous and emotionally present.',
    education: { degree: 'M.Tech Computer Science', institution: 'IIT Madras', field: 'Engineering' },
    profession: { title: 'Principal Engineer', company: 'Razorpay', income: '₹48 LPA' },
    location: { city: 'Bangalore', state: 'Karnataka', country: 'India', nativePlace: 'Chennai' },
    family: { father: 'Mr. V. Iyer (Retired ISRO scientist)', mother: 'Mrs. Rama Iyer (Math teacher)', siblings: 'One younger sister (Doctor, AIIMS)', familyType: 'Nuclear', values: 'Tamil Iyer Brahmin, traditional with progressive outlook' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Carnatic music', 'Reading', 'Coding side projects', 'Trekking'], languages: ['Tamil', 'English', 'Hindi'] },
    religion: { religion: 'Hindu', community: 'Tamil Brahmin', subCommunity: 'Iyer' },
    partnerExpectations: 'An engineer, doctor, or academic who values family, learning, and quiet living. Age 26-30.',
    createdAt: '2025-08-22T10:00:00Z', featured: true,
  },
  {
    id: 'p-groom-aditya', slug: 'aditya-reddy', type: 'groom',
    name: 'Dr. Aditya Reddy', age: 28, height: '5\'11"', maritalStatus: 'Never Married',
    photos: PHOTOS.aditya,
    headline: 'Cardiologist who plays competitive chess',
    about: 'I am a third-year cardiology resident at Apollo Hyderabad. Between shifts I play online chess and try to keep a 1800+ rating. I want a partner who balances me out — someone who brings warmth where I bring focus.',
    education: { degree: 'MBBS, MD Medicine, DM Cardiology (pursuing)', institution: 'AIIMS Delhi / Apollo Hyderabad', field: 'Medicine' },
    profession: { title: 'Senior Resident', company: 'Apollo Hospitals', income: '₹28 LPA' },
    location: { city: 'Hyderabad', state: 'Telangana', country: 'India', nativePlace: 'Guntur' },
    family: { father: 'Dr. S. R. Reddy (Orthopedic surgeon)', mother: 'Dr. Vimala Reddy (Pediatrician)', siblings: 'One elder sister (Dermatologist)', familyType: 'Nuclear, all-doctors', values: 'Telugu Reddy, vegetarian, traditional' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Chess', 'Long-distance running', 'Reading', 'Cooking'], languages: ['Telugu', 'English', 'Hindi'] },
    religion: { religion: 'Hindu', community: 'Telugu', subCommunity: 'Reddy' },
    partnerExpectations: 'A doctor, CA, or software professional. Age 25-29. Should be family-oriented and value a medical career.',
    createdAt: '2025-08-30T10:00:00Z',
  },
  {
    id: 'p-groom-vivaan', slug: 'vivaan-patel', type: 'groom',
    name: 'Vivaan Patel', age: 29, height: '6\'0"', maritalStatus: 'Never Married',
    photos: PHOTOS.vivaan,
    headline: 'Civil engineer with a startup for sustainable housing',
    about: 'I run a startup that builds low-cost, earthquake-resistant homes for rural Maharashtra. I split my week between construction sites in Satara and design meetings in Pune. I need a partner who is proud of building things.',
    education: { degree: 'B.Tech Civil Engineering', institution: 'IIT Roorkee', field: 'Engineering' },
    profession: { title: 'Co-founder & CEO', company: 'Bhaumyaan Homes', income: '₹24 LPA (variable)' },
    location: { city: 'Pune', state: 'Maharashtra', country: 'India', nativePlace: 'Ahmedabad' },
    family: { father: 'Mr. Hasmukh Patel (Real estate developer)', mother: 'Mrs. Heena Patel (School trustee)', siblings: 'One younger sister (Architect)', familyType: 'Joint', values: 'Gujarati Patel, traditional, vegetarian, teetotaler' },
    lifestyle: { diet: 'Vegetarian (Jain-friendly)', hobbies: ['Cycling', 'Reading architecture', 'Garba', 'Cooking'], languages: ['Gujarati', 'Hindi', 'English', 'Marathi'] },
    religion: { religion: 'Hindu', community: 'Gujarati', subCommunity: 'Patel (Leuva)' },
    partnerExpectations: 'An MBA, architect, or designer from a traditional Gujarati family. Age 26-30.',
    createdAt: '2025-09-02T10:00:00Z',
  },
  {
    id: 'p-groom-reyansh', slug: 'reyansh-kapoor', type: 'groom',
    name: 'Reyansh Kapoor', age: 31, height: '6\'1"', maritalStatus: 'Never Married',
    photos: PHOTOS.reyansh,
    headline: 'Third-generation restaurateur',
    about: 'I run a small chain of farm-to-table restaurants across Delhi NCR, sourcing from my family farm in Himachal. Looking for someone who loves food, travel, and the right kind of chaos.',
    education: { degree: 'B.A. Hospitality, MBA', institution: 'Les Roches Switzerland / ISB', field: 'Hospitality' },
    profession: { title: 'Managing Director', company: 'Kapoor Hospitality Group', income: '₹85 LPA (variable)' },
    location: { city: 'Delhi', state: 'Delhi', country: 'India', nativePlace: 'Shimla' },
    family: { father: 'Mr. Sanjeev Kapoor (Hotel mogul)', mother: 'Mrs. Pooja Kapoor (Interior designer)', siblings: 'One younger sister (Fashion PR)', familyType: 'Joint, business family', values: 'Punjabi Hindu, liberal, foodie, non-vegetarian at home' },
    lifestyle: { diet: 'Non-vegetarian', hobbies: ['Cooking', 'Travel', 'Wine tasting', 'Skiing'], languages: ['Hindi', 'English', 'Punjabi', 'French'] },
    religion: { religion: 'Hindu', community: 'Punjabi', subCommunity: 'Khatri' },
    partnerExpectations: 'A designer, MBA, or food professional. Age 27-32. Should love travel and culture.',
    createdAt: '2025-09-06T10:00:00Z', featured: true,
  },
  {
    id: 'p-groom-aarav', slug: 'aarav-mehta', type: 'groom',
    name: 'Aarav Mehta', age: 28, height: '5\'9"', maritalStatus: 'Never Married',
    photos: PHOTOS.aarav,
    headline: 'Data scientist working on climate models',
    about: 'I build ML models for weather prediction at a research lab in Pune. I love the monsoon — I track its arrival obsessively. Looking for someone who notices the small things too.',
    education: { degree: 'M.S. Data Science', institution: 'IIT Bombay', field: 'Research' },
    profession: { title: 'Senior Data Scientist', company: 'CSTEP', income: '₹28 LPA' },
    location: { city: 'Pune', state: 'Maharashtra', country: 'India', nativePlace: 'Surat' },
    family: { father: 'Mr. Nilesh Mehta (Diamond merchant)', mother: 'Mrs. Mili Mehta (School teacher)', siblings: 'One younger brother (Studying CA)', familyType: 'Nuclear', values: 'Gujarati Lohana, vegetarian, modern' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Weather tracking', 'Photography', 'Cycling', 'Chess'], languages: ['English', 'Hindi', 'Gujarati'] },
    religion: { religion: 'Hindu', community: 'Gujarati', subCommunity: 'Lohana' },
    partnerExpectations: 'A scientist, engineer, or artist. Age 25-29. Should love books and long conversations.',
    createdAt: '2025-09-07T10:00:00Z',
  },
  {
    id: 'p-groom-vihaan', slug: 'vihaan-joshi', type: 'groom',
    name: 'Vihaan Joshi', age: 30, height: '5\'11"', maritalStatus: 'Never Married',
    photos: PHOTOS.vihaan,
    headline: 'Hotelier restoring a haveli in Jaipur',
    about: 'I am restoring my grandfather\'s haveli in the old city of Jaipur into a boutique hotel. I split time between Jaipur and Udaipur. Looking for someone who appreciates craft, color, and quiet evenings.',
    education: { degree: 'B.A. Hospitality', institution: 'Oberoi Centre, Delhi', field: 'Hospitality' },
    profession: { title: 'General Manager', company: 'Haveli 1932', income: '₹38 LPA' },
    location: { city: 'Jaipur', state: 'Rajasthan', country: 'India', nativePlace: 'Jaipur' },
    family: { father: 'Late Mr. K. Joshi (Royal family, banker)', mother: 'Mrs. Rukmini Joshi (Philanthropist)', siblings: 'One elder brother (Software architect, US)', familyType: 'Old Rajasthani family', values: 'Marwari Brahmin, traditional vegetarian, cultured' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Heritage restoration', 'Miniature painting', 'Classical music', 'Yoga'], languages: ['Hindi', 'English', 'Marwari', 'Sanskrit'] },
    religion: { religion: 'Hindu', community: 'Rajasthani', subCommunity: 'Brahmin (Joshi)' },
    partnerExpectations: 'An art historian, designer, or doctor from a cultured family. Age 26-30. Should appreciate heritage and traditions.',
    createdAt: '2025-09-09T10:00:00Z',
  },
  {
    id: 'p-groom-muhammad', slug: 'muhammad-khan', type: 'groom',
    name: 'Muhammad Khan', age: 29, height: '5\'11"', maritalStatus: 'Never Married',
    photos: PHOTOS.muhammad,
    headline: 'Architect designing mosques and cultural centers',
    about: 'I work with a small architecture firm in Lucknow designing mosques, schools, and cultural centers across North India. I love Urdu poetry, Awadhi cuisine, and the call to prayer at sunset. Looking for a partner who values faith and intellect equally.',
    education: { degree: 'M.Arch', institution: 'CEPT Ahmedabad', field: 'Architecture' },
    profession: { title: 'Senior Architect', company: 'Aga Khan Trust for Culture', income: '₹22 LPA' },
    location: { city: 'Lucknow', state: 'Uttar Pradesh', country: 'India', nativePlace: 'Lucknow' },
    family: { father: 'Prof. J. K. Khan (Historian, AMU)', mother: 'Mrs. Nuzhat Khan (School principal)', siblings: 'Two younger sisters — one doctor, one studying law', familyType: 'Joint, academic', values: 'Muslim Sunni, educated liberal family' },
    lifestyle: { diet: 'Non-vegetarian (halal)', hobbies: ['Reading Urdu poetry', 'Architecture', 'Cricket', 'Cooking'], languages: ['Urdu', 'Hindi', 'English', 'Arabic'] },
    religion: { religion: 'Muslim', community: 'Sunni', subCommunity: 'Syed' },
    partnerExpectations: 'A professional from a progressive Muslim family. Age 26-30. Should value education, culture, and family.',
    createdAt: '2025-09-11T10:00:00Z', featured: true,
  },
  {
    id: 'p-groom-arnav', slug: 'arnav-singh', type: 'groom',
    name: 'Captain Arnav Singh', age: 32, height: '6\'0"', maritalStatus: 'Never Married',
    photos: PHOTOS.arnav,
    headline: 'Commercial pilot with a passion for mountains',
    about: 'I fly long-haul for a major Indian carrier. My layovers take me to places like Reykjavik and Cape Town. Looking for someone to explore the world with — and a partner who understands the rhythm of an unconventional schedule.',
    education: { degree: 'B.Tech Aeronautical, Commercial Pilot License', institution: 'IIT Kanpur / Indira Gandhi Aviation Academy', field: 'Aviation' },
    profession: { title: 'Captain', company: 'Air India', income: '₹78 LPA' },
    location: { city: 'Chandigarh', state: 'Punjab', country: 'India', nativePlace: 'Patiala' },
    family: { father: 'Air Marshal (Retd.) H. S. Singh', mother: 'Mrs. Manjit Kaur (Homemaker)', siblings: 'One younger brother (Army officer)', familyType: 'Military, nuclear', values: 'Sikh Jat, modern Sikh, vegetarian' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Trekking', 'Skydiving', 'Aviation history', 'Reading'], languages: ['Punjabi', 'Hindi', 'English'] },
    religion: { religion: 'Sikh', community: 'Punjabi', subCommunity: 'Jat' },
    partnerExpectations: 'A professional who is independent, well-traveled, and adaptable. Age 27-31. From a respectable family.',
    createdAt: '2025-09-13T10:00:00Z',
  },
  {
    id: 'p-groom-ishaan', slug: 'ishaan-bose', type: 'groom',
    name: 'Ishaan Bose', age: 28, height: '5\'9"', maritalStatus: 'Never Married',
    photos: PHOTOS.ishaan,
    headline: 'Musician and music producer',
    about: 'I am a sitarist and producer based in Kolkata, composing for films and collaborating with indie bands. I play late, sleep late, and make the best chai in the city. Looking for someone who treats music and life as one practice.',
    education: { degree: 'B.A. Music (Sitar)', institution: 'Rabindra Bharati University', field: 'Music' },
    profession: { title: 'Independent Musician & Producer', company: 'Self-employed', income: '₹12 LPA (variable)' },
    location: { city: 'Kolkata', state: 'West Bengal', country: 'India', nativePlace: 'Shantiniketan' },
    family: { father: 'Mr. Ananda Bose (Classical vocalist)', mother: 'Mrs. Anuradha Bose (Dance teacher)', siblings: 'One younger sister (Painter)', familyType: 'Joint, artistic', values: 'Bengali Brahmin, liberal, non-vegetarian-friendly' },
    lifestyle: { diet: 'Pescatarian', hobbies: ['Sitar', 'Composing', 'Reading Tagore', 'Cooking'], languages: ['Bengali', 'English', 'Hindi'] },
    religion: { religion: 'Hindu', community: 'Bengali', subCommunity: 'Brahmin' },
    partnerExpectations: 'An artist, writer, or teacher who values depth and creative chaos. Age 25-29.',
    createdAt: '2025-09-16T10:00:00Z',
  },
  {
    id: 'p-groom-dhruv', slug: 'dhruv-malhotra', type: 'groom',
    name: 'Dhruv Malhotra', age: 30, height: '6\'0"', maritalStatus: 'Never Married',
    photos: PHOTOS.dhruv,
    headline: 'Litigation lawyer fighting environmental cases',
    about: 'I am a partner at a Delhi boutique law firm specializing in environmental and climate litigation. Outside court, I am on my motorbike exploring the highways around Delhi-Rajasthan. Looking for someone who has conviction and warmth.',
    education: { degree: 'BA LLB Hons', institution: 'National Law School, Bangalore', field: 'Law' },
    profession: { title: 'Partner', company: 'Mishra & Malhotra', income: '₹52 LPA' },
    location: { city: 'Delhi', state: 'Delhi', country: 'India', nativePlace: 'Delhi' },
    family: { father: 'Justice (Retd.) R. K. Malhotra', mother: 'Mrs. Alka Malhotra (Environmental activist)', siblings: 'One elder brother (Investment banker, Singapore)', familyType: 'Nuclear', values: 'Punjabi Khatri, liberal, non-vegetarian at home' },
    lifestyle: { diet: 'Non-vegetarian', hobbies: ['Motorcycling', 'Reading', 'Climate activism', 'Cricket'], languages: ['Hindi', 'English', 'Punjabi'] },
    religion: { religion: 'Hindu', community: 'Punjabi', subCommunity: 'Khatri' },
    partnerExpectations: 'A lawyer, journalist, or activist. Age 27-31. Should have a strong sense of purpose.',
    createdAt: '2025-09-17T10:00:00Z', featured: true,
  },
  {
    id: 'p-groom-krishna', slug: 'krishna-pillai', type: 'groom',
    name: 'Krishna Pillai', age: 29, height: '5\'10"', maritalStatus: 'Never Married',
    photos: PHOTOS.krishna,
    headline: 'Marine biologist exploring the Andamans',
    about: 'I am a marine biologist working on coral reef restoration. I spend three months a year on research boats off the Andaman Islands and the rest writing papers from my flat in Chennai. Looking for a partner who can be at home in any port.',
    education: { degree: 'PhD Marine Biology', institution: 'Annamalai University', field: 'Research' },
    profession: { title: 'Research Scientist', company: 'NCSCM Chennai', income: '₹18 LPA' },
    location: { city: 'Chennai', state: 'Tamil Nadu', country: 'India', nativePlace: 'Kollam' },
    family: { father: 'Mr. G. K. Pillai (Retired Naval officer)', mother: 'Mrs. Latha Pillai (Botany professor)', siblings: 'One younger brother (Doctor, UK)', familyType: 'Nuclear', values: 'Kerala Nair, traditional vegetarian, modern' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Scuba diving', 'Sailing', 'Reading', 'Birdwatching'], languages: ['Malayalam', 'Tamil', 'English', 'Hindi'] },
    religion: { religion: 'Hindu', community: 'Kerala', subCommunity: 'Nair' },
    partnerExpectations: 'A doctor, researcher, or teacher who values exploration and balance. Age 26-30.',
    createdAt: '2025-09-18T10:00:00Z',
  },
  {
    id: 'p-groom-ayaan', slug: 'ayaan-ahmed', type: 'groom',
    name: 'Dr. Ayaan Ahmed', age: 31, height: '5\'10"', maritalStatus: 'Never Married',
    photos: PHOTOS.ayaan,
    headline: 'Orthopedic surgeon who plays competitive squash',
    about: 'I lead the sports medicine unit at a Bangalore hospital. I run a free clinic every Sunday for underprivileged athletes. Looking for a partner who shares my energy and ambitions.',
    education: { degree: 'MBBS, MS Ortho', institution: 'KEM Hospital Mumbai / AIIMS', field: 'Medicine' },
    profession: { title: 'Senior Consultant Orthopedic Surgeon', company: 'Manipal Hospital', income: '₹48 LPA' },
    location: { city: 'Bangalore', state: 'Karnataka', country: 'India', nativePlace: 'Mumbai' },
    family: { father: 'Dr. Imran Ahmed (Pediatric surgeon)', mother: 'Dr. Rehana Ahmed (Gynecologist)', siblings: 'Two siblings — both doctors', familyType: 'Nuclear, medical family', values: 'Muslim Sunni Bohri, educated liberal' },
    lifestyle: { diet: 'Non-vegetarian (halal)', hobbies: ['Squash', 'Trekking', 'Reading', 'Cooking'], languages: ['English', 'Urdu', 'Hindi'] },
    religion: { religion: 'Muslim', community: 'Sunni', subCommunity: 'Bohri' },
    partnerExpectations: 'A doctor, lawyer, or CA. Age 27-31. From a progressive Muslim family.',
    createdAt: '2025-09-19T10:00:00Z',
  },
  {
    id: 'p-groom-atharv', slug: 'atharv-nair', type: 'groom',
    name: 'Atharv Nair', age: 28, height: '5\'9"', maritalStatus: 'Never Married',
    photos: PHOTOS.atharv,
    headline: 'Independent filmmaker with two festival wins',
    about: 'My debut feature premiered at Busan last year. I split my time between Kerala sets and Mumbai pitching sessions. I am looking for someone who sees the world as stories waiting to be told.',
    education: { degree: 'BFA Film Direction', institution: 'FTII Pune', field: 'Film' },
    profession: { title: 'Filmmaker', company: 'Independent', income: '₹16 LPA (variable)' },
    location: { city: 'Kochi', state: 'Kerala', country: 'India', nativePlace: 'Kochi' },
    family: { father: 'Mr. K. N. Nair (Documentary filmmaker)', mother: 'Mrs. Maya Nair (Costume designer)', siblings: 'One elder sister (Sound designer)', familyType: 'Nuclear, artistic', values: 'Kerala Nair, progressive, vegetarian-friendly' },
    lifestyle: { diet: 'Pescatarian', hobbies: ['Filmmaking', 'Reading scripts', 'Cinema', 'Yoga'], languages: ['Malayalam', 'English', 'Hindi', 'Tamil'] },
    religion: { religion: 'Hindu', community: 'Kerala', subCommunity: 'Nair' },
    partnerExpectations: 'An artist, designer, or writer who appreciates cinema. Age 25-29.',
    createdAt: '2025-09-20T10:00:00Z',
  },
  {
    id: 'p-groom-kabir', slug: 'kabir-verma', type: 'groom',
    name: 'Prof. Kabir Verma', age: 30, height: '5\'11"', maritalStatus: 'Never Married',
    photos: PHOTOS.kabir,
    headline: 'English literature professor at St. Stephen\'s',
    about: 'I teach Romantic poetry and lead the annual Shakespeare production. I live in a flat in Civil Lines full of books and badly-tuned guitars. Looking for someone who would argue with me about Keats over chai.',
    education: { degree: 'MPhil English Literature, PhD (pursuing)', institution: 'Delhi University / Oxford', field: 'Academia' },
    profession: { title: 'Assistant Professor', company: 'St. Stephen\'s College', income: '₹16 LPA' },
    location: { city: 'Delhi', state: 'Delhi', country: 'India', nativePlace: 'Lucknow' },
    family: { father: 'Mr. Ashok Verma (Civil servant, IAS)', mother: 'Dr. Shalini Verma (Sociologist)', siblings: 'Two siblings — one IAS, one studying law', familyType: 'Nuclear', values: 'UP Kayastha, liberal, vegetarian' },
    lifestyle: { diet: 'Vegetarian', hobbies: ['Reading', 'Theatre', 'Writing poetry', 'Cycling'], languages: ['Hindi', 'English', 'Urdu'] },
    religion: { religion: 'Hindu', community: 'UP', subCommunity: 'Kayastha' },
    partnerExpectations: 'A teacher, editor, or researcher who values language and ideas. Age 26-30.',
    createdAt: '2025-09-21T10:00:00Z', featured: true,
  },
];

export const seedInquiries: Inquiry[] = [
  {
    id: 'inq-1',
    name: 'Sunita Patel',
    email: 'sunita.p@gmail.com',
    phone: '+91 98765 43210',
    subject: 'Profile inquiry for my son',
    message: 'Namaste, I came across your platform and would like to enquire about a few profiles for my son. He is 31, a software engineer based in Pune.',
    profileId: 'p-bride-aanya',
    createdAt: '2025-09-23T14:23:00Z',
    status: 'new',
  },
  {
    id: 'inq-2',
    name: 'Ravi Krishnan',
    email: 'ravi.krishnan@outlook.com',
    phone: '+91 99887 76655',
    subject: 'Membership upgrade',
    message: 'I would like to upgrade my family membership to the Heart tier. Please share the next steps.',
    createdAt: '2025-09-22T09:15:00Z',
    status: 'read',
  },
];

export const seedUsers: User[] = [
  {
    id: 'u-1',
    email: 'admin@marriageguide.in',
    name: 'Aanya Sharma',
    role: 'admin',
    status: 'active',
    joinedAt: '2024-12-01T10:00:00Z',
  },
  {
    id: 'u-2',
    email: 'priya.iyer@example.com',
    name: 'Priya Iyer',
    role: 'member',
    status: 'active',
    joinedAt: '2025-08-20T10:00:00Z',
  },
  {
    id: 'u-3',
    email: 'arjun.sharma@example.com',
    name: 'Arjun Sharma',
    role: 'member',
    status: 'active',
    joinedAt: '2025-08-15T10:00:00Z',
  },
];

export const seedJournal: JournalEntry[] = [
  {
    id: 'j-1',
    slug: 'art-of-the-first-meeting',
    title: 'The Art of the First Meeting: A Modern Matchmaker\'s Guide',
    excerpt: 'Why the first coffee is never really about coffee — and how to make it count.',
    body: 'In an age of infinite swipes, the first meeting has become more precious than ever...',
    cover: 'https://images.unsplash.com/photo-1542596594-649edbc13630?auto=format&fit=crop&w=1400&q=80',
    author: 'Aanya Sharma',
    date: '2025-09-15',
    readTime: '6 min',
    tags: ['matchmaking', 'advice'],
  },
  {
    id: 'j-2',
    slug: 'rethinking-arranged-marriage',
    title: 'Rethinking the Arranged Marriage: Tradition Meets Choice',
    excerpt: 'How modern Indian families are rewriting the rules of matchmaking without losing their soul.',
    body: 'The word "arranged" carries centuries of weight. But today, a new generation is reclaiming it...',
    cover: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1400&q=80',
    author: 'Aanya Sharma',
    date: '2025-09-01',
    readTime: '8 min',
    tags: ['tradition', 'culture'],
  },
  {
    id: 'j-3',
    slug: 'craft-of-the-biodata',
    title: 'The Craft of the Biodata: Telling Your Story Without Sounding Like a CV',
    excerpt: 'Five principles for writing a marriage biodata that feels like you.',
    body: 'A biodata is the most important document you will write this year. It is also the most personal...',
    cover: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1400&q=80',
    author: 'Aanya Sharma',
    date: '2025-08-20',
    readTime: '5 min',
    tags: ['profile', 'advice'],
  },
  {
    id: 'j-4',
    slug: 'weddings-as-art',
    title: 'Weddings as Art: Why the Small Details Matter Most',
    excerpt: 'A meditation on florals, fonts, and the quiet work of making a day unforgettable.',
    body: 'Every wedding is a small opera. The costumes, the set, the music — and the singular fact that everyone you love is in the same room...',
    cover: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1400&q=80',
    author: 'Aanya Sharma',
    date: '2025-08-05',
    readTime: '7 min',
    tags: ['wedding', 'culture'],
  },
  {
    id: 'j-5',
    slug: 'meet-the-parents',
    title: 'Meet the Parents: A Field Guide for the Modern Couple',
    excerpt: 'Practical wisdom and small courtesies for that most Indian of occasions.',
    body: 'There is no social event quite like the first "meet the parents." It is theatre, diplomacy, and a job interview rolled into one...',
    cover: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?auto=format&fit=crop&w=1400&q=80',
    author: 'Aanya Sharma',
    date: '2025-07-22',
    readTime: '6 min',
    tags: ['advice', 'family'],
  },
  {
    id: 'j-6',
    slug: 'language-of-compromise',
    title: 'The Language of Compromise: What Long Marriages Teach Us',
    excerpt: 'Notes from a hundred couples on what made their partnership last.',
    body: 'I spent the last six months interviewing couples who have been married for forty years and longer. The pattern was unmistakable...',
    cover: 'https://images.unsplash.com/photo-1494774157365-9888e5d3a8a1?auto=format&fit=crop&w=1400&q=80',
    author: 'Aanya Sharma',
    date: '2025-07-10',
    readTime: '9 min',
    tags: ['marriage', 'wisdom'],
  },
];

export const seedTestimonials: Testimonial[] = [
  {
    id: 't-1',
    couple: 'Riya & Vivaan',
    quote: 'Marriage Guide felt less like a service and more like a letter from a wise old friend. We were engaged four months after joining.',
    story: 'We met through the curated matches, but it was the conversations with our relationship manager that gave us confidence.',
    date: '2025-08-15',
    photo: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 't-2',
    couple: 'Ananya & Reyansh',
    quote: 'I had almost given up. Within six weeks, I was having dinner with the woman who is now my wife.',
    story: 'The profiles felt curated, real, and warm. Not the parade of strangers I had grown used to.',
    date: '2025-07-22',
    photo: 'https://images.unsplash.com/photo-1525258946800-98cfd641d0de?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 't-3',
    couple: 'Zoya & Ayaan',
    quote: 'As a Muslim woman, finding a platform that respected our values without making us feel "different" was a revelation.',
    story: 'The matchmaking team understood the nuances of Bohri families and introduced us with care.',
    date: '2025-09-02',
    photo: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 't-4',
    couple: 'Diya & Aarav',
    quote: 'Both of us work in tech and had no time for the usual process. Marriage Guide did the work of a hundred coffee dates for us.',
    story: 'We were introduced to three profiles, said yes to the second, and married within the year.',
    date: '2025-06-30',
    photo: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 't-5',
    couple: 'Kavya & Muhammad',
    quote: 'I was nervous about an inter-community match. The team handled my parents with so much grace.',
    story: 'We are now married in Hyderabad, with a fusion nikah-and-telugu wedding that honored both our families.',
    date: '2025-05-18',
    photo: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 't-6',
    couple: 'Tara & Reyansh',
    quote: 'The platform feels like a small atelier — every profile is treated with care, and so is every introduction.',
    story: 'I recommend it to every single friend who asks.',
    date: '2025-04-09',
    photo: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
  },
];

export const seedSuccessStories: SuccessStory[] = [
  {
    id: 's-1',
    bride: 'Riya Bose',
    groom: 'Vivaan Patel',
    city: 'Mumbai',
    weddingDate: '2025-08-15',
    story: 'A textile designer from Kolkata and a civil engineer from Pune met through a curated introduction. They were engaged in the rain at the steps of a Goan church.',
    photo: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 's-2',
    bride: 'Ananya Kapoor',
    groom: 'Reyansh Kapoor',
    city: 'Delhi',
    weddingDate: '2025-07-22',
    story: 'Two Kapoors met at a vintage Bollywood film screening in Hauz Khas, both separately invited by their relationship managers. They were engaged within a month.',
    photo: 'https://images.unsplash.com/photo-1525258946800-98cfd641d0de?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 's-3',
    bride: 'Zoya Ahmed',
    groom: 'Ayaan Ahmed',
    city: 'Bangalore',
    weddingDate: '2025-09-02',
    story: 'Two Bohri professionals met for the first time at a calligraphy workshop organized by Marriage Guide. They married within four months in a ceremony honoring both their families.',
    photo: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 's-4',
    bride: 'Kavya Reddy',
    groom: 'Muhammad Khan',
    city: 'Hyderabad',
    weddingDate: '2025-05-18',
    story: 'An architect restoring Nizami homes and an architect designing cultural spaces met over a shared love of old Hyderabad. Their nikah-telugu wedding was featured in Vogue India.',
    photo: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=800&q=80',
  },
];
